#if !defined(AFX_BORDER_H__4FA1833B_1F0E_4F6B_9E6E_F88054D36060__INCLUDED_)
#define AFX_BORDER_H__4FA1833B_1F0E_4F6B_9E6E_F88054D36060__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CBorder wrapper class

class CBorder : public COleDispatchDriver
{
public:
	CBorder() {}		// Calls COleDispatchDriver default constructor
	CBorder(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CBorder(const CBorder& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	VARIANT GetColor();
	void SetColor(VARIANT* newValue);
	VARIANT GetLineStyle();
	void SetLineStyle(long nNewValue);
	LPDISPATCH GetParent();
	VARIANT GetWeight();
	void SetWeight(long nNewValue);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_BORDER_H__4FA1833B_1F0E_4F6B_9E6E_F88054D36060__INCLUDED_)
