#if !defined(AFX_FILTERS_H__9C25BEC3_021C_4313_B847_061F823A5301__INCLUDED_)
#define AFX_FILTERS_H__9C25BEC3_021C_4313_B847_061F823A5301__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CFilter;

/////////////////////////////////////////////////////////////////////////////
// CFilters wrapper class

class CFilters : public COleDispatchDriver
{
public:
	CFilters() {}		// Calls COleDispatchDriver default constructor
	CFilters(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CFilters(const CFilters& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	long GetCount();
	CFilter GetItem(long Index);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_FILTERS_H__9C25BEC3_021C_4313_B847_061F823A5301__INCLUDED_)
