#if !defined(AFX_NTERIOR_H__C556438C_008B_4059_AC17_E5A266033563__INCLUDED_)
#define AFX_NTERIOR_H__C556438C_008B_4059_AC17_E5A266033563__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// Cnterior wrapper class

class Cnterior : public COleDispatchDriver
{
public:
	Cnterior() {}		// Calls COleDispatchDriver default constructor
	Cnterior(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	Cnterior(const Cnterior& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	VARIANT GetColor();
	void SetColor(VARIANT* newValue);
	LPDISPATCH GetParent();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_NTERIOR_H__C556438C_008B_4059_AC17_E5A266033563__INCLUDED_)
