#if !defined(AFX_PANES_H__D26DAEA8_FF3E_416C_9149_B13ECF86D8BD__INCLUDED_)
#define AFX_PANES_H__D26DAEA8_FF3E_416C_9149_B13ECF86D8BD__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CPane;

/////////////////////////////////////////////////////////////////////////////
// CPanes wrapper class

class CPanes : public COleDispatchDriver
{
public:
	CPanes() {}		// Calls COleDispatchDriver default constructor
	CPanes(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CPanes(const CPanes& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	long GetCount();
	CPane GetItem(long Index);
	LPDISPATCH GetParent();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_PANES_H__D26DAEA8_FF3E_416C_9149_B13ECF86D8BD__INCLUDED_)
