#if !defined(AFX_PROTECTION_H__ED138B98_C4F9_4DC2_839E_A6F6CE2E586E__INCLUDED_)
#define AFX_PROTECTION_H__ED138B98_C4F9_4DC2_839E_A6F6CE2E586E__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CProtection wrapper class

class CProtection : public COleDispatchDriver
{
public:
	CProtection() {}		// Calls COleDispatchDriver default constructor
	CProtection(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CProtection(const CProtection& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	BOOL GetEnabled();
	void SetEnabled(BOOL bNewValue);
	BOOL GetAllowSizingAllRows();
	void SetAllowSizingAllRows(BOOL bNewValue);
	BOOL GetAllowSizingAllColumns();
	void SetAllowSizingAllColumns(BOOL bNewValue);
	BOOL GetAllowInsertingRows();
	void SetAllowInsertingRows(BOOL bNewValue);
	BOOL GetAllowInsertingColumns();
	void SetAllowInsertingColumns(BOOL bNewValue);
	BOOL GetAllowDeletingRows();
	void SetAllowDeletingRows(BOOL bNewValue);
	BOOL GetAllowDeletingColumns();
	void SetAllowDeletingColumns(BOOL bNewValue);
	BOOL GetAllowSorting();
	void SetAllowSorting(BOOL bNewValue);
	BOOL GetAllowFiltering();
	void SetAllowFiltering(BOOL bNewValue);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_PROTECTION_H__ED138B98_C4F9_4DC2_839E_A6F6CE2E586E__INCLUDED_)
