#if !defined(AFX_TITLEBAR_H__241056C4_8E38_4E33_AC01_C8281C8CAEB7__INCLUDED_)
#define AFX_TITLEBAR_H__241056C4_8E38_4E33_AC01_C8281C8CAEB7__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class COWCFont;
class Cnterior;

/////////////////////////////////////////////////////////////////////////////
// CTitleBar wrapper class

class CTitleBar : public COleDispatchDriver
{
public:
	CTitleBar() {}		// Calls COleDispatchDriver default constructor
	CTitleBar(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CTitleBar(const CTitleBar& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	COWCFont GetFont();
	Cnterior GetInterior();
	LPDISPATCH GetParent();
	CString GetCaption();
	void SetCaption(LPCTSTR lpszNewValue);
	BOOL GetVisible();
	void SetVisible(BOOL bNewValue);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_TITLEBAR_H__241056C4_8E38_4E33_AC01_C8281C8CAEB7__INCLUDED_)
