#if !defined(AFX_WEBCALC_H__1C29D227_C96B_4254_97BF_BE9FB293911B__INCLUDED_)
#define AFX_WEBCALC_H__1C29D227_C96B_4254_97BF_BE9FB293911B__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CRange;
class CPane;
class CWorksheet;
class CTitleBar;

/////////////////////////////////////////////////////////////////////////////
// CWebCalc wrapper class

class CWebCalc : public CWnd
{
protected:
	DECLARE_DYNCREATE(CWebCalc)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0x2e510, 0x0, 0x0, { 0xc0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x46 } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:

// Operations
public:
	void AddIn(LPDISPATCH AddIn);
	CRange Intersect(LPDISPATCH Range1, LPDISPATCH Range2);
	CRange Union(LPDISPATCH Range1, LPDISPATCH Range2);
	void BeginUndo();
	void EndUndo();
	void Undo();
	void Refresh();
	void LoadText(LPCTSTR File, LPCTSTR Delimiters, BOOL ConsecutiveDelimAsOne, LPCTSTR TextQualifier);
	void UpdatePropertyToolbox();
	CRange GetActiveCell();
	CPane GetActivePane();
	CWorksheet GetActiveSheet();
	BOOL GetAllowPropertyToolbox();
	void SetAllowPropertyToolbox(BOOL bNewValue);
	CRange GetCells();
	CRange GetColumns();
	BOOL GetDirty();
	void SetDirty(BOOL bNewValue);
	BOOL GetDisplayColHeaders();
	void SetDisplayColHeaders(BOOL bNewValue);
	BOOL GetDisplayGridlines();
	void SetDisplayGridlines(BOOL bNewValue);
	BOOL GetDisplayHorizontalScrollBar();
	void SetDisplayHorizontalScrollBar(BOOL bNewValue);
	BOOL GetDisplayPropertyToolbox();
	void SetDisplayPropertyToolbox(BOOL bNewValue);
	BOOL GetDisplayRowHeaders();
	void SetDisplayRowHeaders(BOOL bNewValue);
	BOOL GetDisplayTitleBar();
	void SetDisplayTitleBar(BOOL bNewValue);
	BOOL GetDisplayToolbar();
	void SetDisplayToolbar(BOOL bNewValue);
	BOOL GetDisplayVerticalScrollBar();
	void SetDisplayVerticalScrollBar(BOOL bNewValue);
	BOOL GetAutoFit();
	void SetAutoFit(BOOL bNewValue);
	VARIANT GetMaxHeight();
	void SetMaxHeight(const VARIANT& newValue);
	VARIANT GetMaxWidth();
	void SetMaxWidth(const VARIANT& newValue);
	BOOL GetEnableAutoCalculate();
	void SetEnableAutoCalculate(BOOL bNewValue);
	BOOL GetEnableEvents();
	void SetEnableEvents(BOOL bNewValue);
	CString GetHTMLData();
	void SetHTMLData(LPCTSTR lpszNewValue);
	CString GetHtmlurl();
	void SetHtmlurl(LPCTSTR lpszNewValue);
	CString GetCSVData();
	void SetCSVData(LPCTSTR lpszNewValue);
	CString GetCsvurl();
	void SetCsvurl(LPCTSTR lpszNewValue);
	CString GetDataType();
	void SetDataType(LPCTSTR lpszNewValue);
	BOOL GetMoveAfterReturn();
	void SetMoveAfterReturn(BOOL bNewValue);
	long GetMoveAfterReturnDirection();
	void SetMoveAfterReturnDirection(long nNewValue);
	CRange GetRange(const VARIANT& Cell1, const VARIANT& Cell2);
	BOOL GetRightToLeft();
	void SetRightToLeft(BOOL bNewValue);
	CRange GetRows();
	BOOL GetScreenUpdating();
	void SetScreenUpdating(BOOL bNewValue);
	CRange GetSelection();
	CTitleBar GetTitleBar();
	CString GetViewableRange();
	void SetViewableRange(LPCTSTR lpszNewValue);
	CString GetVersion();
	BOOL GetEnableUndo();
	void SetEnableUndo(BOOL bNewValue);
	BOOL GetCanUndo();
	LPDISPATCH GetConstants();
	long GetMajorVersion();
	CString GetMinorVersion();
	CString GetBuildNumber();
	CString GetRevisionNumber();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_WEBCALC_H__1C29D227_C96B_4254_97BF_BE9FB293911B__INCLUDED_)
