#ifndef __cplusplus
  #error This program can be only compiled in C++ Mode.
#endif

#if !defined(__PMKDEFINES_H)
  #include<PmkInc\PmkDefs.h>
#endif

#if !defined(__PMKARGUMENTS_H)
  #include<PmkInc\PmkArgs.h>
#endif

  #include<PmkInc\PmkDefs.un1>

#if !defined(__PMK100_H)
  #include<PmkInc\Pmk100.h>
#endif

#if !defined(__PMKCUR_DAT)
  #include<PmkDat\PmkCur.dat>
#endif

#if !defined(__PMKHZK_DAT)
  #include<PmkDat\PmkHzk.dat>
#endif
