#if !defined(AFX_CRITERIA_H__9B45D1F7_7E4A_4940_808B_86B64716E700__INCLUDED_)
#define AFX_CRITERIA_H__9B45D1F7_7E4A_4940_808B_86B64716E700__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CCriteria wrapper class

class CCriteria : public COleDispatchDriver
{
public:
	CCriteria() {}		// Calls COleDispatchDriver default constructor
	CCriteria(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CCriteria(const CCriteria& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	void Add(LPCTSTR Criterion);
	long GetCount();
	VARIANT GetItem(long Index);
	BOOL GetShowAll();
	void SetShowAll(BOOL bNewValue);
	long GetFilterFunction();
	void SetFilterFunction(long nNewValue);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_CRITERIA_H__9B45D1F7_7E4A_4940_808B_86B64716E700__INCLUDED_)
