#if !defined(AFX_FILTER_H__395FB1C5_FA58_499A_895E_69B6656FB0D3__INCLUDED_)
#define AFX_FILTER_H__395FB1C5_FA58_499A_895E_69B6656FB0D3__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CCriteria;

/////////////////////////////////////////////////////////////////////////////
// CFilter wrapper class

class CFilter : public COleDispatchDriver
{
public:
	CFilter() {}		// Calls COleDispatchDriver default constructor
	CFilter(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CFilter(const CFilter& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	CCriteria GetCriteria();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_FILTER_H__395FB1C5_FA58_499A_895E_69B6656FB0D3__INCLUDED_)
