#if !defined(AFX_HYPERLINK_H__3132CDEB_8AD4_4BD0_AB37_1DD093424052__INCLUDED_)
#define AFX_HYPERLINK_H__3132CDEB_8AD4_4BD0_AB37_1DD093424052__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CHyperlink wrapper class

class CHyperlink : public COleDispatchDriver
{
public:
	CHyperlink() {}		// Calls COleDispatchDriver default constructor
	CHyperlink(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CHyperlink(const CHyperlink& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	void Delete();
	void Follow(BOOL NewWindow);
	CString GetAddress();
	void SetAddress(LPCTSTR lpszNewValue);
	CString GetName();
	void SetName(LPCTSTR lpszNewValue);
	LPDISPATCH GetParent();
	CString GetSubaddress();
	void SetSubaddress(LPCTSTR lpszNewValue);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_HYPERLINK_H__3132CDEB_8AD4_4BD0_AB37_1DD093424052__INCLUDED_)
