#if !defined(AFX_OWCFONT_H__17E4CE9D_E6A9_44DA_A707_71F92DE92D2E__INCLUDED_)
#define AFX_OWCFONT_H__17E4CE9D_E6A9_44DA_A707_71F92DE92D2E__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// COWCFont wrapper class

class COWCFont : public COleDispatchDriver
{
public:
	COWCFont() {}		// Calls COleDispatchDriver default constructor
	COWCFont(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	COWCFont(const COWCFont& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	VARIANT GetBold();
	void SetBold(BOOL bNewValue);
	VARIANT GetColor();
	void SetColor(VARIANT* newValue);
	VARIANT GetItalic();
	void SetItalic(BOOL bNewValue);
	VARIANT GetName();
	void SetName(LPCTSTR lpszNewValue);
	LPDISPATCH GetParent();
	VARIANT GetSize();
	void SetSize(long nNewValue);
	VARIANT GetUnderline();
	void SetUnderline(long nNewValue);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_OWCFONT_H__17E4CE9D_E6A9_44DA_A707_71F92DE92D2E__INCLUDED_)
