#if !defined(AFX_PANE_H__126D5181_EAC0_44F4_9CE4_F5FF35BD7819__INCLUDED_)
#define AFX_PANE_H__126D5181_EAC0_44F4_9CE4_F5FF35BD7819__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CRange;

/////////////////////////////////////////////////////////////////////////////
// CPane wrapper class

class CPane : public COleDispatchDriver
{
public:
	CPane() {}		// Calls COleDispatchDriver default constructor
	CPane(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CPane(const CPane& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	LPDISPATCH GetParent();
	CRange GetVisibleRange();
	long GetIndex();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_PANE_H__126D5181_EAC0_44F4_9CE4_F5FF35BD7819__INCLUDED_)
