// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "worksheet.h"

// Dispatch interfaces referenced by this interface
#include "range.h"
#include "panes.h"
#include "Protection.h"
#include "autofilter.h"


/////////////////////////////////////////////////////////////////////////////
// CWorksheet properties

/////////////////////////////////////////////////////////////////////////////
// CWorksheet operations

void CWorksheet::Calculate()
{
	InvokeHelper(0x60020000, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CWorksheet::Export(LPCTSTR FileName, long ExportAction)
{
	static BYTE parms[] =
		VTS_BSTR VTS_I4;
	InvokeHelper(0x60020001, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 FileName, ExportAction);
}

void CWorksheet::Scroll(LPDISPATCH Range)
{
	static BYTE parms[] =
		VTS_DISPATCH;
	InvokeHelper(0x60020002, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 Range);
}

VARIANT CWorksheet::Eval(LPCTSTR Formula)
{
	VARIANT result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x60020003, DISPATCH_METHOD, VT_VARIANT, (void*)&result, parms,
		Formula);
	return result;
}

void CWorksheet::ShowAllData()
{
	InvokeHelper(0x60020004, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

CRange CWorksheet::GetCells()
{
	LPDISPATCH pDispatch;
	InvokeHelper(0x60020005, DISPATCH_PROPERTYGET, VT_DISPATCH, (void*)&pDispatch, NULL);
	return CRange(pDispatch);
}

CRange CWorksheet::GetColumns()
{
	LPDISPATCH pDispatch;
	InvokeHelper(0x60020006, DISPATCH_PROPERTYGET, VT_DISPATCH, (void*)&pDispatch, NULL);
	return CRange(pDispatch);
}

BOOL CWorksheet::GetEnableAutoCalculate()
{
	BOOL result;
	InvokeHelper(0x3f1, DISPATCH_PROPERTYGET, VT_BOOL, (void*)&result, NULL);
	return result;
}

void CWorksheet::SetEnableAutoCalculate(BOOL bNewValue)
{
	static BYTE parms[] =
		VTS_BOOL;
	InvokeHelper(0x3f1, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 bNewValue);
}

BOOL CWorksheet::GetEnableAutoFilter()
{
	BOOL result;
	InvokeHelper(0x60020009, DISPATCH_PROPERTYGET, VT_BOOL, (void*)&result, NULL);
	return result;
}

void CWorksheet::SetEnableAutoFilter(BOOL bNewValue)
{
	static BYTE parms[] =
		VTS_BOOL;
	InvokeHelper(0x60020009, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 bNewValue);
}

BOOL CWorksheet::GetFreezePanes()
{
	BOOL result;
	InvokeHelper(0x3f4, DISPATCH_PROPERTYGET, VT_BOOL, (void*)&result, NULL);
	return result;
}

CPanes CWorksheet::GetPanes()
{
	LPDISPATCH pDispatch;
	InvokeHelper(0x6002000c, DISPATCH_PROPERTYGET, VT_DISPATCH, (void*)&pDispatch, NULL);
	return CPanes(pDispatch);
}

LPDISPATCH CWorksheet::GetParent()
{
	LPDISPATCH result;
	InvokeHelper(0x6002000d, DISPATCH_PROPERTYGET, VT_DISPATCH, (void*)&result, NULL);
	return result;
}

CProtection CWorksheet::GetProtection()
{
	LPDISPATCH pDispatch;
	InvokeHelper(0x6002000e, DISPATCH_PROPERTYGET, VT_DISPATCH, (void*)&pDispatch, NULL);
	return CProtection(pDispatch);
}

CRange CWorksheet::GetRange(const VARIANT& Cell1, const VARIANT& Cell2)
{
	LPDISPATCH pDispatch;
	static BYTE parms[] =
		VTS_VARIANT VTS_VARIANT;
	InvokeHelper(0x6002000f, DISPATCH_PROPERTYGET, VT_DISPATCH, (void*)&pDispatch, parms,
		&Cell1, &Cell2);
	return CRange(pDispatch);
}

CRange CWorksheet::GetRows()
{
	LPDISPATCH pDispatch;
	InvokeHelper(0x60020010, DISPATCH_PROPERTYGET, VT_DISPATCH, (void*)&pDispatch, NULL);
	return CRange(pDispatch);
}

CRange CWorksheet::GetUsedRange()
{
	LPDISPATCH pDispatch;
	InvokeHelper(0x60020011, DISPATCH_PROPERTYGET, VT_DISPATCH, (void*)&pDispatch, NULL);
	return CRange(pDispatch);
}

CString CWorksheet::GetViewableRange()
{
	CString result;
	InvokeHelper(0x3fe, DISPATCH_PROPERTYGET, VT_BSTR, (void*)&result, NULL);
	return result;
}

void CWorksheet::SetViewableRange(LPCTSTR lpszNewValue)
{
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x3fe, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 lpszNewValue);
}

CRange CWorksheet::GetVisibleRange()
{
	LPDISPATCH pDispatch;
	InvokeHelper(0x60020014, DISPATCH_PROPERTYGET, VT_DISPATCH, (void*)&pDispatch, NULL);
	return CRange(pDispatch);
}

CAutoFilter CWorksheet::GetAutoFilter()
{
	LPDISPATCH pDispatch;
	InvokeHelper(0x60020015, DISPATCH_PROPERTYGET, VT_DISPATCH, (void*)&pDispatch, NULL);
	return CAutoFilter(pDispatch);
}

BOOL CWorksheet::GetAutoFilterMode()
{
	BOOL result;
	InvokeHelper(0x60020016, DISPATCH_PROPERTYGET, VT_BOOL, (void*)&result, NULL);
	return result;
}

void CWorksheet::SetAutoFilterMode(BOOL bNewValue)
{
	static BYTE parms[] =
		VTS_BOOL;
	InvokeHelper(0x60020016, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 bNewValue);
}

BOOL CWorksheet::GetFilterMode()
{
	BOOL result;
	InvokeHelper(0x60020018, DISPATCH_PROPERTYGET, VT_BOOL, (void*)&result, NULL);
	return result;
}
