
#pragma once


#define FILE_DEVICE_PRIVUTIL			0x8001		// 0..7FFF is reserved for M$
#define FUNCTION_GET_VERSION			0xb00
#define FUNCTION_CRIT_PROC			0xb01

#define IOCTL_READ_BANKS  (CTL_CODE(FILE_DEVICE_MCA, FUNCTION_READ_BANKS,\
		(METHOD_BUFFERED),(FILE_READ_ACCESS|FILE_WRITE_ACCESS)))

#define PRIVUTIL_GET_VERSION	\
	(CTL_CODE(FILE_DEVICE_PRIVUTIL, FUNCTION_GET_VERSION, METHOD_BUFFERED, FILE_READ_ACCESS))

#define PRIVUTIL_CRIT_PROC	\
	(CTL_CODE(FILE_DEVICE_PRIVUTIL, FUNCTION_CRIT_PROC, METHOD_BUFFERED, FILE_READ_ACCESS))
