// PureCOM.idl : IDL source for PureCOM.dll
//

// This file will be processed by the MIDL tool to
// produce the type library (PureCOM.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";

[
	uuid(00000000-4341-FFC0-0004-486954656368),
	version(1.0),
	helpstring("CaPureCOM 1.0 Type Library")
]
library CaPureCOMLib
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");


	[
		uuid(00000000-4341-FFC0-0001-486954656368),
		dual,
		oleautomation,
		helpstring("ICaPureDog")
	] interface ICaPureDog : IDispatch {
		HRESULT	shout();
	};

	[
		uuid(00000000-4341-FFC0-0017-486954656368),
		helpstring("ICaPureDogEvents")
	] dispinterface ICaPureDogEvents {
		properties:
		methods:
			[id(1), helpstring("onBitten 在shout后触发")]
			void onBitten();
	};

	[
		uuid(00000000-4341-FFC0-0002-486954656368),
		helpstring("CaPureDog, 使用纯粹COM技术实现的狗")
	] coclass CaPureDog {
		[default]interface ICaPureDog;
		[default, source]dispinterface ICaPureDogEvents;
	};

};
