// idl_Lab.idl : IDL source for idl_Lab.dll
//

// This file will be processed by the MIDL tool to
// produce the type library (idl_Lab.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";

[
	uuid(3D1F6C9E-3E6A-46D8-9B02-34C907F73127),
	version(1.0),
	helpstring("idl_Lab 1.0 Type Library")
]
library IDL_LABLib
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");

	[uuid(10000000-3E6A-46D8-9B02-34C907F73127)]
	interface I1 : IDispatch {
		[id(1)]HRESULT f1(int a);
	};
	[uuid(10000001-3E6A-46D8-9B02-34C907F73127)]
	interface I2 : I1 {
		//[id(1)]HRESULT f1(int a);
		[id(2)]HRESULT f2();
	};

	[
		object,
		uuid(4C210737-8C2C-453A-9EEF-8208AE5B43D4),
		dual,
		helpstring("IRedeclare Interface"),
		pointer_default(unique)
	]
	interface IRedeclare : IDispatch
	{
		HRESULT f1([in]IDispatch *pDisp1);
	};

	[
		uuid(43289783-3278-6489-2345-678932312890)
	] dispinterface IRedeclareEvents {
		properties:
		methods:
			[id(1000)]void E1();
	};

	[
		uuid(34096CD0-C731-4630-BB45-68B5915740C3),
		helpstring("Redeclare Class")
	]
	coclass Redeclare
	{
		[default] interface IRedeclare;
	};

};
