import "OeSO.idl";

[
	uuid(00000000-4F45-0632-0001-486954656368),
	dual,
	oleautomation,
	helpstring("IOeSOClassesCollection")
] interface IOeSOClassesCollection : IDispatch {
	[id(0), propget, helpstring("获取一个指定类")]
	HRESULT member([in]VARIANT whichmember, [out, retval]IOeSOClass **ret);
};
