VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
  Persistable = 0  'NotPersistable
  DataBindingBehavior = 0  'vbNone
  DataSourceBehavior  = 0  'vbNone
  MTSTransactionMode  = 0  'NotAnMTSObject
END
Attribute VB_Name = "ShapeOutline"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = True
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Explicit

Sub NotImplemented()
    Err.Raise -1, , "Not implemented"
End Sub

Public Property Get visible() As Boolean
    NotImplemented
End Property

Public Property Let visible(ByVal newValue As Boolean)
    NotImplemented
End Property

Public Property Get left() As Integer
    NotImplemented
End Property

Public Property Let left(ByVal newLeft As Integer)
    NotImplemented
End Property

Public Property Get top() As Integer
    NotImplemented
End Property

Public Property Let top(ByVal newTop As Integer)
    NotImplemented
End Property

Public Property Get width() As Integer
    NotImplemented
End Property

Public Property Let width(ByVal newWidth As Integer)
    NotImplemented
End Property

Public Property Get height() As Integer
    NotImplemented
End Property

Public Property Let height(ByVal newHeight As Integer)
    NotImplemented
End Property

Public Property Get fillColor() As Long
    NotImplemented
End Property

Public Property Let fillColor(ByVal newColor As Long)
    NotImplemented
End Property

Public Property Get borderColor() As Long
    NotImplemented
End Property

Public Property Let borderColor(ByVal newColor As Long)
    NotImplemented
End Property

Public Property Get transparency() As Integer
    NotImplemented
End Property

Public Property Let transparency(ByVal newTransparency As Integer)
    NotImplemented
End Property

Public Function clickTest(ByVal x As Integer, ByVal y As Integer) As Boolean
    NotImplemented
End Function
