#ifndef __PMK100_H
	#define __PMK100_H

	#if !defined(__TIME_H)
	  #include<time.h>
	#endif

	#if !defined(__PMKMATH_H)
	  #include<PmkInc\PmkMath.h>
	#endif

	#if !defined(__PMKMEMORY_H)
	  #include<PmkInc\PmkMem.h>
	#endif

	#if !defined(__PMKMOUSECLASS_H)
	  #include<PmkInc\PmkMouse.h>
	#endif

	#if !defined(__PMKCLEARSCREENEXPERT_H)
	  #include<PmkInc\PmkCls.h>
	#endif

	#if !defined(__PMKDRAW_H)
	  #include<PmkInc\PmkDraw.h>
	#endif

	#if !defined(__PMKZK_H)
	  #include<PmkInc\PmkZK.h>
	#endif

	#if !defined(__AUTODETECTDISK_H)
	  #include<PmkInc\PmkDisk.h>
	#endif

	#if !defined(__PMKSERVICES_H)
	  #include<PmkInc\PmkServ.h>
	#endif

	#if !defined(__PMKFILE_H)
	  #include<PmkInc\PmkFile.h>
	#endif

#endif