#ifndef __PMKMEMORY_H
  #define __PMKMEMORY_H

  #if !defined(__STDLIB_H)
    #include<stdlib.h>
  #endif

  #if !defined(__STDIO_H)
    #include<stdio.h>
  #endif

  #if !defined(__IO_H)
    #include<io.h>
  #endif

  #if !defined(__DOS_H)
    #include<dos.h>
  #endif
  #if !defined(__ALLOC_H)
    #include<alloc.h>
  #endif

  #if !defined(__STRING_H)
    #include<string.h>
  #endif

  #if !defined(__MEM_H)
    #include<mem.h>
  #endif

#endif