/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class HelloClient */

#ifndef _Included_HelloClient
#define _Included_HelloClient
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     HelloClient
 * Method:    ShowMessage
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_HelloClient_ShowMessage
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
