VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
  Persistable = 0  'NotPersistable
  DataBindingBehavior = 0  'vbNone
  DataSourceBehavior  = 0  'vbNone
  MTSTransactionMode  = 0  'NotAnMTSObject
END
Attribute VB_Name = "IBuilder"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Explicit

' @TAG-CLASS

Public Enum ErrorConstants
    errInvalidMessage = 40000
End Enum

Public Function Build(ByVal Message As String, Optional ByVal Fontname As String) As String

End Function

Public Function BuildWithUI() As String

End Function
