import "OeSO.idl";

[
	uuid(00000000-4F45-0631-0001-486954656368),
	dual,
	oleautomation,
	helpstring("IOeSOInterfacesCollection")
] interface IOeSOInterfacesCollection : IDispatch {
	[id(0), propget, helpstring("获取一个指定接口")]
	HRESULT member([in]VARIANT whichmember, [out, retval]IOeSOInterface **ret);
};
