// atl2.idl : IDL source for atl2.dll
//

// This file will be processed by the MIDL tool to
// produce the type library (atl2.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";

[
	uuid(ABFF46A0-9AA8-45E3-B40C-80EC5549A917),
	version(1.0),
	helpstring("atl2 1.0 Type Library")
]
library ATL2Lib
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");

};
