#if !defined(AFX_OLEDISPATCHDRIVERPICTURE_H__AE084AB7_B551_4480_A0B5_C45C7DC06F1C__INCLUDED_)
#define AFX_OLEDISPATCHDRIVERPICTURE_H__AE084AB7_B551_4480_A0B5_C45C7DC06F1C__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// COleDispatchDriverPicture wrapper class

class COleDispatchDriverPicture : public COleDispatchDriver
{
public:
	COleDispatchDriverPicture() {}		// Calls COleDispatchDriver default constructor
	COleDispatchDriverPicture(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	COleDispatchDriverPicture(const COleDispatchDriverPicture& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:
	long GetHandle();
	long GetHPal();
	void SetHPal(long);
	short GetType();
	long GetWidth();
	long GetHeight();

// Operations
public:
	// method 'Render' not emitted because of invalid return type or parameter type
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_OLEDISPATCHDRIVERPICTURE_H__AE084AB7_B551_4480_A0B5_C45C7DC06F1C__INCLUDED_)
