/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class UseObjects */

#ifndef _Included_UseObjects
#define _Included_UseObjects
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     UseObjects
 * Method:    changeObject
 * Signature: (LMyJavaClass;)V
 */
JNIEXPORT void JNICALL Java_UseObjects_changeObject
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
