VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
  Persistable = 0  'NotPersistable
  DataBindingBehavior = 0  'vbNone
  DataSourceBehavior  = 0  'vbNone
  MTSTransactionMode  = 0  'NotAnMTSObject
END
Attribute VB_Name = "Class1"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = True
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = True
Option Explicit
Public Function unk(a)

End Function
Public Function unk2(ByVal a)

End Function
Public Function obj(a As Object)

End Function
Public Function bool(a As Boolean)

End Function
Public Function bool2(ByVal a As Boolean)

End Function
Public Function arr(a())

End Function
Public Function param(ParamArray x())

End Function
Public Function opt1(Optional ByVal x As Long = 123)

End Function
