// DogCat.idl : IDL source for DogCat.dll
//

// This file will be processed by the MIDL tool to
// produce the type library (DogCat.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";


interface ICaDog;
interface ICaCat;
interface ICaEarthquake;
interface ICaHorse;
interface ICaPlane;

[
	uuid(00000000-4341-FFE0-0004-486954656368),
	version(1.0),
	helpstring("CampoAccelerate.DogCat testor for COM clients")
]
library CaDogCatLib
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");


[
	uuid(00000000-4341-FFE0-0001-486954656368),
	dual,
	oleautomation
] interface ICaDog : IDispatch {
	HRESULT		shout();
	HRESULT		bornCat([out, retval]ICaCat **ret);
	HRESULT		bornDog([out, retval]ICaDog **ret);
};

[
	uuid(00000000-4341-FFE0-0007-486954656368),
	helpstring("ICaDogEvents")
] dispinterface ICaDogEvents {
	properties:
	methods:
		[id(1)]void shouted();
};

[
	uuid(00000000-4341-FFE1-0001-486954656368),
	dual,
	oleautomation
] interface ICaCat : IDispatch {
	HRESULT shout();
	HRESULT catshout();
};

	[
		uuid(00000000-4341-FFE0-0002-486954656368)
	] coclass CaDog {
		[default]interface ICaDog;
		[default, source]dispinterface ICaDogEvents;
	};

	[
		uuid(00000000-4341-FFE1-0002-486954656368)
	] coclass CaCat {
		[default]interface ICaCat;
	};

	[
		uuid(00000000-4341-FFE3-0001-486954656368),
		dual,
		oleautomation,
		helpstring("ICaEarthquake")
	] interface ICaEarthquake : IDispatch {
		HRESULT quakeNow();
	};

	[
		uuid(00000000-4341-FFE4-0001-486954656368),
		helpstring("ICaEarthquakeEvents")
	] dispinterface ICaEarthquakeEvents {
		properties:
		methods:
			[id(2000001)]void onQuake();
	};

	[
		uuid(00000000-4341-FFE3-0002-486954656368),
		helpstring("CaEarthquake")
	] coclass CaEarthquake {
		[default]interface ICaEarthquake;
		[source]dispinterface ICaEarthquakeEvents;
	};


	[
		uuid(00000000-4341-FFE5-0001-486954656368),
		helpstring("ICaHorse")
	] dispinterface ICaHorse {
		properties:
		methods:
			[id(2000001)]void run();
	};

	[
		uuid(00000000-4341-FFE5-0002-486954656368),
		helpstring("CaHorse, horse class derived from dispinterface")
	] coclass CaHorse {
		[default]dispinterface ICaHorse;
	};

	[
		uuid(00000000-4341-FFE6-0001-486954656368),
		dual,
		oleautomation,
		helpstring("ICaPlane")
	] interface ICaPlane : IDispatch {
		HRESULT fly();
	};

	[
		uuid(00000000-4341-FFE6-0017-486954656368),
		helpstring("ICaPlaneEvents")
	] dispinterface ICaPlaneEvents {
		properties:
		methods:
			[id(1)]void onCrashed();
	};

	[
		object,
		uuid(7ADFF5A5-3CE9-4E93-92A0-1EC38B09BA19),
		dual,
		helpstring("ICaBomb Interface"),
		pointer_default(unique)
	]
	interface ICaBomb : IDispatch
	{
		[id(1), helpstring("method bomb")] HRESULT bomb();
		[propget, id(2), helpstring("property p1")] HRESULT p1([out, retval] long *pVal);
		[propput, id(2), helpstring("property p1")] HRESULT p1([in] long newVal);
	};

	[
		uuid(00000000-4341-FFE6-0002-486954656368),
		helpstring("CaPlane, demonstrate the plane crashed events-based system")
	] coclass CaPlane {
		[default]interface ICaPlane;
		[default, source]dispinterface ICaPlaneEvents;
	};


	[
		uuid(A2264F9F-35E7-4D88-B662-E349D439225D),
		helpstring("CaBomb Class")
	]
	coclass CaBomb
	{
		[default] interface ICaBomb;
	};
};
