VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
  Persistable = 0  'NotPersistable
  DataBindingBehavior = 0  'vbNone
  DataSourceBehavior  = 0  'vbNone
  MTSTransactionMode  = 0  'NotAnMTSObject
END
Attribute VB_Name = "SystemEventListener"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = True
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = True
Option Explicit
Option Base 0

' Tag Class

Public Enum SystemEventConstants
    vbxMemoryLow = 1
    vbxNetworkConnected
    vbxNetworkDisconnected
End Enum

Public Sub Handler(ByVal e As SystemEventConstants, Parameters)
End Sub
